### ISSUE TITLE
Keycloak missing config?

### ISSUE THREAD

**Issue by billbarni** [camunda-community-hub/camunda-8-lowcode-ui-template#100]
I keep getting this error:

![image](https://github.com/camunda-community-hub/camunda-8-lowcode-ui-template/assets/21037830/d0a4c8bf-93c1-4239-aa31-02e4c2a9c24f)

Please could you make the authentication/authorization documentation a little bit more clear on what is needed?

**Comment by chDame** [comment]
Hi @billbarni,

You're right, I should try to improve the doc a little bit. Indeed, you should create the keycloak client CustomTasklist and provide the valid redirect uri in that client (the address of your custom application, probably http://localhost:8080).

Hop that helps

**Comment by billbarni** [comment]
Thank you very much for the input.
