### ISSUE TITLE
Adopt form.io integration

### ISSUE THREAD

**Issue by jonathanlukas** [camunda-community-hub/camunda-8-lowcode-ui-template#92]
A while ago, I created a project:

https://github.com/camunda-consulting/camunda-8-code-examples/tree/main/camunda-8-process-application

As this is a snippet, I wanted to sunset it without losing the custom features implemented.

Your project is very advanced, yet you currently do not have 3rd party form providers integrated.

Would something like this belong into this project? @chDame

**Comment by chDame** [comment]
Hi @jonathanlukas,

That would be really cool!

**Comment by chDame** [comment]
Hi @jonathanlukas,

I had to implement it this morning for a colleague. Feel free to improve it! I just created the viewer but didn't do the formBuilder. It would be nice to choose the builder when creating a new form (form-js or form-io) and to open the right builder when modifying an existing form.

**Comment by jonathanlukas** [comment]
Hi @chDame ,

I just reviewed it and I like it! The only difference to my implementation is (beside vue vs. react) that you are taking the variables as they are and submit them.

I took the leap further to submit modified variables only, however this was mainly because I had to expose them, so I needed to write a mapper function. Using redux, this seems more straight-forward.

I also did not implement the form-editor I have to admit.

For form component selection, I defined a rule that the formKey needs to have a prefix:

`camunda-forms:bpmn:` for camunda forms

`formio-form:bpmn::` for formio forms

followed by the actual form key. 
From your implementation, I can see that you do something similar, but based on different attributes of the IFormViewer.

Would the URI-like pattern be a valid approach?

**Comment by chDame** [comment]
I think that I'll make the distinction between form-io and form-js at creation time. Generator (form-io, form-js) could be a metadata of the form itself (like the name, the modification date, the author) and there would be no need to prefix the formKey.

**Comment by chDame** [comment]
Hi @jonathanlukas,

I just pushed a quick modification to make the formIo builder available. So now, you can choose to use formJs or FormIo at form creation time. For now, I've removed the "preview" button in the formIo builder but I'll bring it back later. Feel free to play around and improve what could be improved :)
